apiVersion: v1
kind: ConfigMap
metadata:
  name: vg-store-java-spring-config
  namespace: vg-store-java-spring-dev
data:
  DRIVER_CLASS_NAME: org.postgresql.Driver
  DATASOURCE_URL: jdbc:postgresql://vg-store-postgres:5432/db_store
  JPA_HIBERNATE_DDL_AUTO: none
  JWT_ALGORITHM: HS256
