apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-store-java-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vg-store-java-spring
  template:
    metadata:
      labels:
        app: vg-store-java-spring
    spec:
      containers:
        - name: vg-store-java-spring
          image: vg-store-java-spring:v1
          ports:
            - containerPort: 8080
          env:
            - name: DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: vg-store-java-spring-config
                  key: DRIVER_CLASS_NAME
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: vg-store-java-spring-config
                  key: DATASOURCE_URL
            - name: JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: vg-store-java-spring-config
                  key: JPA_HIBERNATE_DDL_AUTO
            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: vg-store-java-spring-config
                  key: JWT_ALGORITHM
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vg-store-java-spring-db-secrets
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vg-store-java-spring-db-secrets
                  key: password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: vg-store-java-spring-jwt-secrets
                  key: secret

